name: Tests
on: [push]
jobs:

  linux-test:
    name: Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: install buffalo
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get github.com/gobuffalo/buffalo/buffalo
        buffalo -v

    - name: Test
      run: buffalo test -v -race ./...
